# Moral Considerations and Economic Surplus^[These lecture notes are based on the paper ‘Moral Considerations and Economic Surplus’ (working paper). Please do not distribute these lecture notes without permission.] {#moral}

## Introduction

These lecture notes introduce another definition of economic surplus ('the economic pie’) that allows for moral considerations. It specifically investigates moral considerations related to the normative validity of counting costs and benefits of consumers and producers and external costs as economic social surplus. Why is this important? In the first week we have seen that the classical perspective of economic value rests on four pillars: (*i*) optimisation, (*ii*) equilibrium, (*iii*) empiricism and (*iv*) choice-based normativity. The implication of this perspective is that choices of market actors perfectly track value for society. 

The second week provided an extended perspective using insights from psychology. According to this perspective there can be a difference between choice-based value and experienced based value. Given particular assumptions it can be justified that experienced value is the right metric to measure instead of choice-based value. As we have seen, this has implications for policy interventions related to information provision and externality taxation.

This chapter questions the results of chapter \@ref(surplus) from a different angle: there can be moral considerations related to the choices of market actors that lead to the question whether it is justified to include the value of consumers, producers and the external costs completely in the economic surplus calculation. 

Before moving on, it is useful to illustrate why moral considerations are important. Consider a pork producer who is active in the market for pork. The government has set specific rules for pork production for those who want to become active in this market. With the aim of lowering marginal costs, the pork producer ignores some of these rules related to animal welfare without providing good reasons and without changing external costs. The producer rationally trades off lower marginal costs with the probability of getting a fine when being caught. According to the economic model of value developed in chapter \@ref(surplus) this leads to an *increase* in producer surplus in the market of pork and thereby into an increase is economic surplus. The example suggests that there are normative limits for behaviour by consumers and producers in markets that might not be captured in behavioural choice. 

Or consider a philosopher of animal welfare who considers the eating of pork to be morally problematic because pigs are sentient beings 'like us'. If the reasoning of this philosopher is correct, counting consumer benefits fully as social surplus is likely to be questionable. 

These two examples at least illustrate that the choice-based normativity perspective (chapter \@ref(surplus)) and experienced-based normativity (chapter \@ref(erroreconsurplus)) might not be shared by all persons and groups in society. In these lecture notes we therefore change the 4th pillar 'normativity' from choice-based to morally-based evaluation. 

How to deal with this in cost-benefit analysis? 

The key question to investigate here is: "What should count as 'better or worse off'?" [@atkinson2009economics;@sandel2013market]. This normative question can be investigated from different viewpoints: the individual level, the community level and the societal level. 

At the *individual level*, consumers and producers make moral commitments to their own perspective on the good life. They might want to eat less meat, fly less and might want to lower their carbon emissions by making more sustainable choices. However, these moral commitments and targets are not always reached leading to a discrepancy between the individuals’ perspective on the good life and their actual choices. Most persons are aware of this gap between their goals and actual behaviour in their personal lives. For example, sometimes individuals make promises to particular sustainability targets to others but do not keep these promises. Another example is the observation of flight shame which suggests that individuals have an independent reflective moral attitude (conscience) towards their own behaviour. Even when choices (Chapter \@ref(surplus))  and experiences (Chapter \@ref(erroreconsurplus)) are valuable and decisions are made to buy the product, this suggests that these choices might not be evaluated as truly ‘good’ by the individual.  

At the *community level*, individuals participate in communities who determine (partly or fully) what counts as valuable. Community membership can be voluntary or non-voluntary and membership of communities results in particular duties and customs. Communities entail particular minimum standards of behaviour for consumers and producers based on the community values. These standards can be viewed as partly independent of the preferences that are expressed by consumers and producers in their day-to-day market choices. For example, an activist participating in a ‘climate change community’ is likely to be held accountable for behavioural choices: only ‘telling the truth’ is likely not sufficient according the community standards.

At the *societal level*, individuals participate in the common project of living together. Governments can formulate particular minimal sustainability standards for market participants which in turn can lead to particular duties and customs for market actors. This was illustrated with the example of the pork producer above. Furthermore, governments can ask market participants to make concrete commitments in terms of sustainability. Goals can act as targets for moral excellence and result in obligations. 

In order to count something as valuable for society these different viewpoints can play a role and can result in a discrepancy between choice-based value and morally weighted social value. In line with the results of Chapter \@ref(erroreconsurplus) this can imply that the social optimum is not reached even when there are no external costs. Note that the different viewpoints do not restrict choice of market actors but seek to foster a plural perspective on what should count as valuable.  

The remainder of this chapter is structured as follows. First, Section II gives an overview of several strategies that are employed to deal with moral considerations when valuing market outcomes. This section motivates why an adjustment of economic surplus is needed when moral considerations are present. Section III develops a novel analytical specification of economic surplus and sections IV and V discuss the implications for pricing. Examples are provided along the way. Section VI concludes.

## Dealing with moral considerations at the valuation stage   

### Introduction

This section discusses four general approaches to deal with moral considerations when analysing (changes) in economic social surplus. The first approach is the ethical checkbox approach (section II.B), the second approach is the economizing ethics approach (section II.C), the third approach is the ethicizing economics approach (section II.D). The fourth approach is the qualitative valuation approach (section II.E). These approaches are not necessarily perfect substitutes but can be employed in a complementary way. 

### Ethical checkbox approach

The first approach to deal with moral considerations is the ‘ethical checkbox’ approach (ECH). This approach analyses moral considerations independently of economic surplus assessments using a list of *necessary* ethical requirements or rules for the behaviour of market actors. It is closely related to the ‘independent doctrine’ which views (micro-)economics as separate from ethics [see @high1985economics, p. 4--6, for a brief history]. The advantage of the ECH approach is that it gives room to the realm of moral and ethical reasoning for guiding market practices. This circumvents that ethical considerations are fully overtaken by utilitarian and game-theoretic arguments of economists when policy recommendations are given. When moral considerations are of a different kind than (monetized) utilitarian consumer value or producer profits and transcend consumer and producer choice behaviour such a separation seems useful and justified. When the ethical checkboxes are ticked, micro-economists can employ the standard definition of economic social surplus which is---in the absence of externalities---assumed to be equal to the sum of consumer and producer surplus. 

A disadvantage of the ECH approach is that it ignores the loss of economic social surplus resulting from consumers and producers in the market who do not act according to the ethical checkbox. The example of the pork producer who violated the rules illustrates this. Furthermore, the ECH approach also ignores other moral considerations that are not part of the checkbox but are nevertheless important for individual market actors, the communities they participate in or for society. This is because the standard specification of economic social surplus is based on choice-based normativity (pillar (*iv*)). The ECH approach assumes that costs and benefits should be counted without further normative consideration by the individual, the community or society. Consumer and producer moral responsibility do not enter the equations insofar this responsibility is not fully expressed in the particular market under consideration. The normative evaluation of public policies for markets is of course affected by this implicit assumption of moral *excellence* of market actors. As a result, it is questionable whether the assumed economic social surplus function correctly measures economic social value in the presence of (remaining) moral considerations.

### Economizing ethics approach

The second approach to deal with moral considerations when calculating economic social surplus is the ‘economizing ethics’ approach (ECE). This approach views moral considerations as (monetized) utilitarian internalities or externalities and has been applied to analyse repugnant markets, morality and identity, public policy decisions with an ethical component and regulations in the social domain [@lazear2000economic; @benabou2011identity;  @roth2018marketplaces; @chorus2018taboo; @mouter2021contrasting].

A good aspect of ECE is that it might enhance understanding of individuals choice behaviour when moral considerations for private or public decisions are present [@chorus2015models]. Furthermore, it frankly acknowledges that ignoring moral considerations in markets can lead to a loss of utilitarian value for people inside and outside these markets. @posner2017moral (p. 1812) write: 

> Our simple answer, put too briefly, is that on welfarist grounds, moral commitments can matter, and that when people would suffer a welfare loss when their moral commitments are violated, regulators should ask: how much are people willing to pay to honor those commitments?

And in another section of this paper @posner2017moral (p. 1840) write: "*Our major goal is to acknowledge rather than to resolve the measurement problem and to insist on the basic principle: people **experience** welfare losses from social outcomes that offend their moral commitments, even if those outcomes do not involve their own wealth or health. Private willingness to pay is the best way to measure those losses.*" The ECE approach therefore assumes that all experiences should count including experiences of moral losses or gains by third parties due to the market choices of consumers and producers.

ECE might also explain descriptively why there are societal laws that put restrictions on market trade. This is because the loss of monetized moral value by third parties can go beyond the value of market transactions, but is related to the actual market behaviour of consumers, producers and the regulator. According to the ECE approach, including the monetized utilitarian externalities stemming from moral considerations thereby can lead to better estimates of (changes in) economic surplus. Furthermore, an advantage of the ECE approach for economists is that it can be operationalized using empirical choice data in combination with the micro-econometric toolbox of applied economists. It is possible to ask persons what their willingness to accept is for violating a particular moral consideration in order to measure the external effects.

A disadvantage of the ECE approach is that it often fails to make normative sense for assessments of decisions outside markets. Without acknowledging distinct social domains with their corresponding distinct core values, rules and customs, it feels like bringing the hockey-stick of economic efficiency to join a field where teams play basketball. 

### Ethicizing economics approach

The third approach is the ‘ethicizing economics’ (ETE) approach which is explored in this paper. There are two different ways the ETE approach has been implemented in the literature. First, in the climate change literature, this approach has been pursued to deal with distributional effects using a novel specification of the social welfare function that employs a single ethical perspective such as prioritarianism instead of ECE [@spash1997ethics]. 

The second ETE approach which is pursued in these lecture notes, seeks to operationalise diverse normative ideas about what is socially valuable by re-specifying economic social surplus using ethical parameters. Such a normative *diversity* might even be present at the level of the individual as a mixture of deontological, virtue and consequential arguments play a role in the reflection on behavioural choices of market actors [see @van2007beyond;@white2009defense]. Economists are well equipped to study consequences, but other moral considerations related to duties and virtues have received less attention. What kinds of considerations can we think of?

Deontology is the study of duties:

> The word deontology derives from the Greek words for duty (deon) and science (or study) of (logos). In contemporary moral philosophy, deontology is one of those kinds of normative theories regarding which choices are morally required, forbidden, or permitted. In other words, deontology falls within the domain of moral theories that guide and assess our choices of what we ought to do (deontic theories).[Stanford Encyclopedia of Philosophy](https://plato.stanford.edu/entries/ethics-deontological/)

Deontological moral considerations therefore are therefore related to what market actors ought (not) to do and not what they are actually doing. This type of moral considerations results in particular duties. For now, it is sufficient to notice that such moral considerations can exist for particular markets of interest. 

Moral considerations related to virtue focus on moral character:

> It may, initially, be identified as the one that emphasizes the virtues, or moral character, in contrast to the approach that emphasizes duties or rules (deontology) or that emphasizes the consequences of actions (consequentialism).[Stanford Encyclopedia of Philosophy](https://plato.stanford.edu/entries/ethics-deontological/)

Besides moral character, virtue ethics also focusses on motivations and intentions behind the choices of market actors. According to this perspective, choosing polluting goods for utilitarian reasons is not sufficient when there are no appropriate motivations or reasons given. 

The framework for cost-benefit analysis developed in Chapter \@ref(surplus) does not deal with these moral considerations and leaves out normative reflection at the individual, community and societal level in the calculation stage. For example, a virtue ethicist focussing on sustainability practices might want to count the benefits of flying to Barcelona for the funeral of a family member differently than the marginal benefits of a person who goes 5 times per year on holidays by air travel ‘just for fun’. Motivations can matter for counting benefits and costs according to this view.

The ETE approach acknowledges that the mathematical specification of economic social surplus is a moral enterprise itself and that it can impact economists’ normative recommendations for optimal economic policies. Furthermore, the plural version of it acknowledges that there are multiple reasonable normative positions each resulting in a particular specification of the economic ‘pie’. Counting producer costs and benefits fully---as we did in week Chapter \@ref(surplus)---is just one of the normative perspectives.

Working directly on the economic social surplus function seems to be more in line with the arguments developed by moral philosophers from schools and traditions that focus on virtues and duties. The intuition of the difference between the ECE approach and the ETE approach is illustrated by structuring the argument. The ECE approach proceeds as follows:

(A)	 Consumer choices of market good $Q$ are morally questionable for sound moral considerations $R$.
(B)	Consumer benefits for $Q$ are not adjusted in the economic surplus.
(C)	Additional external costs are counted for violation of moral considerations $R$ by consumers.

This follows the ideas of @posner2017moral who propose to monetize external costs and results in a model that is equivalent to the model in Chapter \@ref(surplus) with additional external cost terms.

The ETE approach instead, deals directly with the moral consideration when specifying the economic surplus:

(A)	Consumer choices of market good $Q$ are morally questionable for sound moral considerations $R$.
(B)	Then in order to account for moral consideration $R$ in studies of the market in $Q$, it is reasonable to adjust the consumer benefits for $Q$ downwards using an ethical parameter.

Both approaches account for moral considerations but do this in a different manner depending on whether researchers find ECE or ETE more appropriate.

### Qualitative valuation approach

The fourth approach to deal with moral considerations is the qualitative valuation (QUV) approach. For this approach the quantitative calculation of exact changes in economic surplus is less relevant. The QUV approach can highlight which values are relevant for normative policy decisions on markets or decisions in other spheres of society [@klamer2017doing;@wempe2018reframing]. 

It is valuable for at least six reasons. First, it can enhance reciprocal understanding of those involved in valuation by fostering the conversation about the values underlying regulatory and market choices. Second, it acknowledges that normative preferences for public policies can partly be socially constructed for example by reading, role switching or by a deliberative process. Third, it is helpful for articulating which moral considerations are relevant for market valuation and why. Fourth, QUV can be helpful for the selection of competent persons for policy decisions. Fifth, an advantage of the QUV approach can be that the conversation is open and not dictated by a pre-defined analytical valuation method. Sixth, qualitative motivations developed by participants in the QUV approach can be helpful for policy makers articulating their motivations for their public policies [see for example @mouter2021contrasting, section 5].

A disadvantage of the QUV approach is that no *quantitative* estimation of impacts and value are provided that allow for a comparison of different economic policy interventions in markets including the status quo of doing nothing. Therefore, quantitative questions such as: ‘how high should an externality tax on good $X$ be?’ or ‘what is the loss of economic social value of changes in the market for $X$?’ cannot be answered using the QUV approach only. A second disadvantage is that it is harder to reach consensus, as heterogeneous opinions are sometimes hard to weigh when they are based on qualitative statements only. A third disadvantage is that the outcomes of the QUV approach depend on the quality of expression of the people who are involved. This might disadvantage those with less rhetorical and verbal qualities. 

### Contributions of the remainder of this chapter

There is no good reason to assume *a priori* that the assumption of moral excellence of consumers, producers and regulators in markets is valid. Furthermore, different groups in society or different experts might define moral excellence in different ways, and in some markets the assumption of moral excellence might be more valid than in others. According to @sen2000discipline (p. 952): 

> sensible cost-benefit analysis demands something beyond the mainstream method, in particular, the invoking of explicit social choice judgments that take us beyond market-centered valuation.

The aim of the remainder of this chapter is to offer a novel specification for the economic pie that allows for diverse normative considerations related to economic social surplus. The methodological approach allows for the inclusion of three kinds of moral considerations. Moral considerations related to: 

(i)	marginal consumer benefits;
(ii)	producer marginal costs;
(iii)	external costs. 

In order to show the impacts for economic policy recommendations, the new conceptualisation of economic social surplus is applied to the optimal taxation of a consumption externality. Such an exercise is useful to gain intuition on how moral considerations and ethical parameters can impact standard economic policy recommendations. The externality taxes seek to efficiently price positive or negative side effects resulting from market transactions while still allowing for trade in the market. But what is defined as ‘efficient’ of course depends on the definition of the economic pie by the researcher. Something, we already discovered in Chapter \@ref(erroreconsurplus). 

### Scope

Before moving on, it is good practice to think about the scope of the model: where can it be applied, and for which decisions can it not be applied? The model of this week is applicable for the analysis of the taxation of a consumption externality in existing markets with remaining moral considerations. It is not applicable for the analysis of whether a market should be opened or closed by a government. This class of policy decisions leads to other kinds of moral considerations related to offering choice opportunities. This raises fundamental freedom questions of which the analysis is beyond the scope of this academic course. 

Furthermore, distributional concerns, price and tax discrimination, bounded rationality of market actors (Chapter \@ref(erroreconsurplus).), strategic firm interactions, limited information, general equilibrium and bargaining between consumers and producers are ignored. This is done for clarity of exposition and argumentation and to stay close to how practical cost-benefit is often operationalized. 

## Redefining the economic pie

###	The advisory committee

This section redefines the economic ‘pie’ for a stylised partial equilibrium model of a single good or service mathematically and graphically. Suppose that an advisory committee is summoned that has $N$ members. Assume that each member $n$ of this advisory committee receives a weight $\omega_n \geq 0$ and that these weights sum up to $1$. Depending on the kind of market, the committee could consist of the full population of a region, city, country or the world, a group of representative elected officials, representatives of particular communities, representatives of responsible advisory institutions, a group of (scientific) experts or a weighted combination of all these groups. Membership of the committee can be based on experience, knowledge and expertise and/or on the degree that the expert represents a community or population of interest or simply on the status of being a citizen.

We will not discuss how this advisory committee *should* look like, what the requirements of membership should be and what the procedural process of deliberation should be. The mathematical description also abstracts away from potential strategic considerations within the advisory committee. 

It is assumed that all normative positions of the committee members are in principle correct or internally consistent and are based on correct information about the consequences of behaviour. This pragmatic assumption is inconsistent with the observation that in the presence of objective moral considerations there can be mutual exclusive positions where given the underlying (meta-)ethical assumptions the moral reasoning of only one or several of the committee members is correct.^[See @singh2020moral for a recent discussion on expert agreement, disagreement and the (non-)existence of objective moral facts.]

### Adjusted consumer surplus

Total monetized consumer benefits for the market are denoted by $\int_0^{Q^*}p(Q)dQ$ where $Q$ is the demand for the good or service. The marginal consumer benefits are given by $p(Q)$. This market inverse demand function reflects the maximum marginal willingness to pay for a group of anonymous consumers and is assumed to be independent of consumers’ income levels.  In equilibrium, marginal consumer benefits are equal to the private costs, resulting in an equilibrium demand of $Q^*$. It is assumed that all consumers all have the same private access costs and pay the same equilibrium price $p^*$ for the good or service. From a normative perspective the assessment of marginal consumption benefits of the consumer as reflected by the consumers’ marginal willingness to pay deserves more investigation. 

When there are moral considerations related to consumers’ marginal benefits, member $n$ of the committee can adjust the consumer benefits with an ethical weight $0 \leq \alpha_n \leq 1$. This adjustment can be based on moral considerations and reasons related to consumer responsibility. Committees can use survey data and interviews to learn more about the reasons and intentions of consumers or investigate whether the consumption choice has been made under free conditions or is the result of addiction. The adjustment of marginal consumer benefits does not entail that choice *should* be restricted or forbidden.  

Moral considerations relating to consumer behaviour can lead to scaling down consumer benefits in particular markets. Eq. \@ref(eq:acs) adjusts the consumer surplus for moral considerations related to consumer marginal benefits: 

\begin{equation}
ACS = \sum_{n=1}^N \omega_n \left(\int_0^{Q^*} \alpha_n p(Q)dQ - p^* Q^*\right) = \bar{\alpha} \int_0^{Q^*} p(Q)dQ - p^* Q^*,
(\#eq:acs)
\end{equation}
where $\bar{\alpha} = \sum_{n=1}^N \omega_n \alpha_n$ is the weighted average sum over all committee members for the ethical parameters for consumer benefits.^[An additional assumption is required for a valid model: at least one committee member needs to have $\alpha_n>0$. It is not necessary to have a weighted average: a majority voting decision on the weights is also possible, although this fully leaves out the normative perspectives of particular minorities in the advisory committee.] In the presence of moral considerations, consumer benefits are therefore adjusted downwards. Adjusted consumer surplus estimates in markets with moral considerations will therefore decrease in comparison to the case where moral excellence of consumers is assumed ($\bar{\alpha} = 1$). 

At this point it is helpful to provide an illustration how the model can be operationalized for practical policy analysis. Suppose an advisory committee on the economic value of the pork market is summoned. There are 10 representatives invited for this committee. Each of them has received an equal weight $\omega_n=0.1$. 

Table 1 below provides an overview of the ethical weights the representatives propose for the marginal benefits of consumers and their reasons for choosing these weights. It includes a wide range of voices and reasons from society, institutes and advocacy groups. 
